a = input('Digite algo: ')
print('O Tipe primitivo desse valor é', type(a))
print('Só tem espaços?', a.isspace())
print('Só tem alfabético?', a.isalpha())
print('Só tem alfanumérico?', a.isalnum())
print('Está em maiúsculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Está em capitalizada?', a.istitle())

a = input('Digite algo: ')
print('O Tipe primitivo desse valor é', type(a))
print('Só tem espaços?', a.isspace())
print('Só tem alfabético?', a.isalpha())
print('Só tem alfanumérico?', a.isalnum())
print('Está em maiúsculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Está em capitalizada?', a.istitle())
